apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-gitops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/minabisa90/end-to-end-devops-gitops-platform.git
    targetRevision: main
    path: helm/flask-app

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
